### ISSUE TITLE
Tables do not render properly

### ISSUE THREAD

**Issue by jmmoore** [spress/spress-theme-spresso#5]
Hello,

My IDE and a GFM preview both render the table on the sample post properly, but neither Chrome nor Firefox renders the table markdown in that way.

Adding some CSS to the table elements will address this, but I don't know if that's the route you wish to go down or not. If so, I'd like to contribute some CSS that would mimic the way that it's rendered in GFM.

![image](https://cloud.githubusercontent.com/assets/6610729/26335871/86ec547c-3f34-11e7-97c5-68db0e187e10.png)

**Comment by yosymfony** [comment]
Thank you man.
